# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0956db0e29cdaeaaf2e36cbdf6ae8bd4aafc6aa7ec9ebf3fcf3069ce228dd8cb2578faa0602e90a8f38779a33f056ad7692b04c2becd183b4284636f9686e023
  week_id: sec
  redis_url: localhost:6379
  sender_email: admin@development.com
  pag_seguro_email: kukinha_cmf785@hotmail.com
  pag_seguro_token: B973D9B43BE24997A9855E6871541C57
test:
  secret_key_base: a590d6bfdfee5f405e1e450a7d11dbdfff0463d391e5454f7f5ac1a17c0e2ea5fff3f3f61a3fc468f167268e57176da47713830e2e392096793addd2460a514d
  week_id: sec
  redis_url: localhost:6379
  sender_email: admin@teste.com
  pag_seguro_email: kukinha_cmf785@hotmail.com
  pag_seguro_token: B973D9B43BE24997A9855E6871541C57
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  week_id: <%= ENV["WEEK_NAME"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  site_domain: <%= ENV["SITE_DOMAIN"] %>
  sendgrid_user: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  sender_email: <%= ENV["ADMIN_EMAIL"] %>
  pag_seguro_email: <%= ENV["PAG_SEGURO_EMAIL"] %>
  pag_seguro_token: <%= ENV["PAG_SEGURO_TOKEN"] %>
