default: &default
  name: Semana em Teste
  email: admin@semanas.com
  sigla: SeT
  colors:
    primary: 87132
    default: FFFFFF
  logo: semana_test-logo.png
  infos:
    conta: XXXX-X
    agencia: XXXX-X
    beneficiado: XXXXXXXXXXXXXXXXXXXXX
    banco: XXXXXXXXXXXXXX
    local: XXXXXXXXXXXXXX
stem:
  <<: *default
  name: Semana de Tecnologia da Engenharia Mecânica
  sigla: STEM
  colors:
    primary: 871328
    default: 871328
  logo: stem-logo.png
  infos:
    local: PET da Engenharia Mecânica
setic:
  <<: *default
sec:
  <<: *default
  name: Semana de Engenharia Civil
  sigla: SEC
  colors:
    primary: 87132
    default: FFFFFF
  logo: sec-logo.png
  infos:
    conta: 23608-X
    agencia: 4439-3
    beneficiado: Jessyca Rosa Sena
    banco: Banco do Brasil
    local: PET da Engenharia Civil
sepro:
  <<: *default
seq:
  <<: *default
  name: Semana de Engenharia Química
  sigla: SEQ
  colors:
    primary: 0D5272
    default: 0D5272
  logo: seq-logo.png
sea:
  <<: *default
